apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
        - name: my-spring-app
          # IMPORTANT: This is a placeholder!
          image: ghcr.io/abderrezakBoukazouha/gtiops-lab:b16a34d
          ports:
            - containerPort: 8080