apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      # This is the new section you need to add!
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: my-spring-app
          image: ghcr.io/abderrezakBoukazouha/gtiops-lab:b16a34d # This will be updated by the next CI run
          ports:
            - containerPort: 8080