apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-service
  namespace: sandbox
spec:
  selector:
    app: my-spring-app
  ports:
    - protocol: TCP
      port: 80 # The port the service is available on
      targetPort: 8080 # The port your Spring app is running on